[env]
RUST_TARGET_PATH = { value = "target-specs", relative = true }

[build]
target = "aarch64-sel4-unwind"

[unstable]
unstable-options = true
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
