[package]
name = "zerok-core"
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"
readme = "README.md"

[features]
default = ["std"]
std = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1"
