name: Deploy documentation

on:
  push:
    branches: [main]
    paths:
      - "book/**" # only changes under book/ trigger
      - ".github/workflows/book.yml" # allow updates to the workflow to retrigger
  workflow_dispatch: {} # still let you run it manually

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install mdBook (and optional plugins)
        run: |
          cargo install mdbook mdbook-linkcheck mdbook-mermaid mdbook-admonish

      - name: Build book
        run: |
          cd book
          mdbook-admonish install
          mdbook-mermaid install
          cd ..
          mdbook build book

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: book/book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
